package controller;

public enum Actions {
  
	ADD_NODE_MENU_ITEM,ADD_IMAGE_MENU_ITEM, SEE_IMAGE_MENU_ITEM, ADD_FILTER_MENU_ITEM, OK_FILTER_CHOOSER_BTN,
	DELETE_NODE_MENU_ITEM, EXPAND_TREE_BTN, COLLAPSE_TREE_BTN;
}
